### ISSUE TITLE
Getting errors and no lxc stats

### ISSUE THREAD

**Issue by kneufeld** [wakeful/pve_exporter#6]
I'm getting the following errors:

    ERRO[0177] json: cannot unmarshal string into Go struct field lxc.disk of type float64  source="pve_exporter.go:486"
    ERRO[0177] json: cannot unmarshal string into Go struct field lxc.maxdisk of type float64  source="pve_exporter.go:486"

and no lxc stats in the `/metrics` output. I am getting qemu output as expected.

```
pve_exporter
 url: https://github.com/wakeful/pve_exporter
 version: 0.1.3
```

Downloaded the release binary.

**Comment by wakeful** [comment]
@kneufeld thanks for reporting - I added a fix to version [v0.1.4](https://github.com/wakeful/pve_exporter/releases/tag/0.1.4)
